###1A, 1B, 1C,1D,1E####
library(forecast)
library(ggplot2)
library(readxl)
mydata<-read_excel("D:/ORBA_Summer Semester  2020/Business Forecasting/DataFiles/DataFiles/GDP_change_2.xlsx")
View(mydata)
myts<-ts(mydata[,2],start = 1963)
estsample<-window(myts,start=1963,end=2011,frequency=1)
plot(estsample)
acf(estsample)
pacf(estsample)
arima1<-arima(estsample,order=c(0,1,1))
summary(arima1)
arima2<-arima(estsample,order=c(1,1,1))
summary(arima2)
arima3<-arima(estsample,order=c(1,1,0))
summary(arima3)

checkresiduals(arima1)
gdpautoarima<-auto.arima(estsample)
summary(gdpautoarima)
checkresiduals(gdpautoarima)
predict(arima1)
predict(arima1,n.ahead = 5)
print(arima1)
moving_avg_3<-forecast(ma(estsample,order = 3,centre = FALSE),h=5)
predict(moving_avg_3,n.ahead=5)
print(moving_avg_3)
moving_avg_7<-forecast(ma(estsample,order = 7,centre = FALSE),h=5)
predict(moving_avg_7,n.ahead=5)
print(moving_avg_7)



###2A,2B,2C,2D,2E####

library(forecast)
library(ggplot2)
library(readxl)
mydata<-read_excel("D:/ORBA_Summer Semester  2020/Business Forecasting/DataFiles/DataFiles/CPI_change_2.xlsx")
View(mydata)
myts<-ts(mydata[,2],start = 1963)
estsample<-window(myts,start=1963,end=2011,frequency=1)
testsample<-window(myts,start=2012,end=2015,frequency=1)
plot(estsample)
acf(estsample)
pacf(estsample)
ndiffs(estsample)
arima1<-arima(estsample,order=c(0,1,1))
summary(arima1)
arima2<-arima(estsample,order=c(1,1,1))
summary(arima2)
arima3<-arima(estsample,order=c(1,0,1))
summary(arima3)
checkresiduals(arima2)
predict(arima2)
predict(arima2,n.ahead = 5)
print(arima2)
naive_forecast<-forecast(naive(estsample),h=4)
predict(naive_forecast,n.ahead=4)
print(naive_forecast)

farima<-function(x,h){forecast(x,model=arima2,h=h)}
e1<-tsCV(testsample,farima,h=4)
fnaive<-function(x,h){forecast(naive(x),h=h)}
e2<-tsCV(testsample,fnaive,h=4)
sqrt(mean(e1^2,na.rm=TRUE)) 
sqrt(mean(e2^2,na.rm=TRUE))

CPI_change_2autoarima<-auto.arima(estsample)
summary(CPI_change_2autoarima)
checkresiduals(CPI_change_2autoarima)


####3A,3B,3C######

library(forecast)
library(ggplot2)
library(readxl)
mydata<-read_excel("D:/ORBA_Summer Semester  2020/Business Forecasting/DataFiles/DataFiles/Netflix_2.xlsx")
View(mydata)
myts<-ts(mydata[,5],start = c(2000,1),end=c(2015,4),frequency=4)
estsample<-window(myts,start=c(2002,2))
plot(estsample)
acf(estsample)
pacf(estsample)
ndiffs(estsample)
arima1<-arima(estsample,order=c(0,1,1))
summary(arima1)
arima2<-arima(estsample,order=c(1,1,1))
summary(arima2)
arima3<-arima(estsample,order=c(2,1,1))
summary(arima3)
checkresiduals(arima2)
netflix_gseries<-auto.arima(estsample)
summary(netflix_gseries)
checkresiduals(netflix_gseries)


#####6#######
library(forecast)
library(ggplot2)
library(readxl)
mydata<-read_excel("D:/ORBA_Summer Semester  2020/Business Forecasting/DataFiles/DataFiles/US_retail_sales_2.xlsx ")
View(mydata)

myts<-ts(mydata[,2],start = c(2001,1),end=c(2015,12),frequency=12)
estsample<-window(myts,start=c(2001,1),end=c(2012,12))

plot(estsample)
acf(estsample)
pacf(estsample)
ndiffs(estsample)

US_retail_sales_2arima<-auto.arima(estsample)
summary(US_retail_sales_2arima)
checkresiduals(US_retail_sales_2arima)